services:
  web:
    build: .
    ports:
      - 3001:3000
    environment:
      SECRET_KEY_BASE: "e55fb68eb0f1f4f82fbb56eafeebf1c134518fd466d1c3d01b2bfd3d6b5cd9347b4c15eecb3bdc0e4c5bc226dba626a23bb7b9ddb14f709638571f910002f639"
      RAILS_LOG_TO_STDOUT: "true"
      REMOTE_USER: blalbrit@stanford.edu
      SETTINGS__CORS__ALLOW_ORIGIN_URL: "http://localhost:3000"
    tty: true
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
      MINIO_UPDATE: off
    command: server /data --json --console-address ':9090'
    ports: ["9000:9000/tcp", "9090:9090/tcp"] # open http://127.0.0.1:9090 (9000 is the API port)
    volumes:
      - minio_data:/data
volumes:
  minio_data:
