name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.4"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Start MinIO
        run: docker compose up -d minio
      - name: Wait for MinIO to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:9000/minio/health/ready; do sleep 2; done'
      - name: Run tests
        run: bin/rake test:prepare spec
      - name: Stop MinIO
        if: always()
        run: docker compose down
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: Lint Ruby files
        run: bin/rubocop --parallel
