name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-202103-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-202103-
    - name: Bundle install
      run: bundle config path vendor/bundle
    - name: Install dependencies
      run: bin/setup
    - name: Run tests
      run: bin/rake
    - name: Run tests (with cocina feature flag enabled)
      run: SETTINGS__FEATURES__COCINA=true bin/rake spec
    - name: Run tests (with OCFL feature flag enabled)
      run: SETTINGS__FEATURES__READ_STACKS_FROM_OCFL_ROOT=true bin/rake spec
